name: "Parent-Child Container Creator"
description: "Creates parent containers and their children (helloworld example)"
inputs:
  parent-container:
    description: "The name of the parent container (A or B)"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"  # This points to the Dockerfile for the environment
  env:
    PARENT_CONTAINER: ${{ inputs.parent-container }}

